# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_s2_cap <- function(x, y, z, height) {
    .Call(`_spatstat_sphere_cpp_s2_cap`, x, y, z, height)
}

